# CMake generated Testfile for 
# Source directory: F:/Projekte/coop/XTools/fontgen/lpng1621
# Build directory: F:/Projekte/coop/XTools/fontgen/lpng1621_build
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(pngtest "./pngtest" "F:/Projekte/coop/XTools/fontgen/lpng1621/pngtest.png")
add_test(pngvalid "./pngvalid")
add_test(pngstest "./pngstest" "F:/Projekte/coop/XTools/fontgen/lpng1621/contrib/pngsuite/basn0g01.png" "F:/Projekte/coop/XTools/fontgen/lpng1621/contrib/pngsuite/basn0g02.png" "F:/Projekte/coop/XTools/fontgen/lpng1621/contrib/pngsuite/basn0g04.png" "F:/Projekte/coop/XTools/fontgen/lpng1621/contrib/pngsuite/basn0g08.png" "F:/Projekte/coop/XTools/fontgen/lpng1621/contrib/pngsuite/basn0g16.png" "F:/Projekte/coop/XTools/fontgen/lpng1621/contrib/pngsuite/basn2c08.png" "F:/Projekte/coop/XTools/fontgen/lpng1621/contrib/pngsuite/basn2c16.png" "F:/Projekte/coop/XTools/fontgen/lpng1621/contrib/pngsuite/basn3p01.png" "F:/Projekte/coop/XTools/fontgen/lpng1621/contrib/pngsuite/basn3p02.png" "F:/Projekte/coop/XTools/fontgen/lpng1621/contrib/pngsuite/basn3p04.png" "F:/Projekte/coop/XTools/fontgen/lpng1621/contrib/pngsuite/basn3p08.png" "F:/Projekte/coop/XTools/fontgen/lpng1621/contrib/pngsuite/basn4a08.png" "F:/Projekte/coop/XTools/fontgen/lpng1621/contrib/pngsuite/basn4a16.png" "F:/Projekte/coop/XTools/fontgen/lpng1621/contrib/pngsuite/basn6a08.png" "F:/Projekte/coop/XTools/fontgen/lpng1621/contrib/pngsuite/basn6a16.png" "F:/Projekte/coop/XTools/fontgen/lpng1621/contrib/pngsuite/ftbbn0g01.png" "F:/Projekte/coop/XTools/fontgen/lpng1621/contrib/pngsuite/ftbbn0g02.png" "F:/Projekte/coop/XTools/fontgen/lpng1621/contrib/pngsuite/ftbbn0g04.png" "F:/Projekte/coop/XTools/fontgen/lpng1621/contrib/pngsuite/ftbbn2c16.png" "F:/Projekte/coop/XTools/fontgen/lpng1621/contrib/pngsuite/ftbbn3p08.png" "F:/Projekte/coop/XTools/fontgen/lpng1621/contrib/pngsuite/ftbgn2c16.png" "F:/Projekte/coop/XTools/fontgen/lpng1621/contrib/pngsuite/ftbgn3p08.png" "F:/Projekte/coop/XTools/fontgen/lpng1621/contrib/pngsuite/ftbrn2c08.png" "F:/Projekte/coop/XTools/fontgen/lpng1621/contrib/pngsuite/ftbwn0g16.png" "F:/Projekte/coop/XTools/fontgen/lpng1621/contrib/pngsuite/ftbwn3p08.png" "F:/Projekte/coop/XTools/fontgen/lpng1621/contrib/pngsuite/ftbyn3p08.png" "F:/Projekte/coop/XTools/fontgen/lpng1621/contrib/pngsuite/ftp0n0g08.png" "F:/Projekte/coop/XTools/fontgen/lpng1621/contrib/pngsuite/ftp0n2c08.png" "F:/Projekte/coop/XTools/fontgen/lpng1621/contrib/pngsuite/ftp0n3p08.png" "F:/Projekte/coop/XTools/fontgen/lpng1621/contrib/pngsuite/ftp1n3p08.png")
