//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEX.IDAL.MDB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class SceneNode
    {

        [Key, Column(Order = 0)]
        public long NodeID { get; set; }
        public Nullable<long> EntID { get; set; }
        [Key, Column(Order = 1)]
        public long SceneID { get; set; }
        public byte[] Data { get; set; }
        public string Name { get; set; }
    }
}
